name: manually build package for openbsd

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - amd64

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-x'

jobs:
  build:

    runs-on: macos-12

    steps:
      - run: brew install openssh

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 4096
          box: generic/openbsd7
          run: |
            run sudo pkg_add curl gtar-- gcc%11

            run sudo ln -s /usr/local/bin/gtar /usr/bin/tar

            export HOME=/home/vagrant
            export LD_LIBRARY_PATH=/usr/local/lib

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod a+x ppkg

            run ./ppkg setup
            run ./ppkg update
            run ./ppkg install ${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }}
            run ./ppkg bundle  ${{ github.event.inputs.package-name }} /home/vagrant/.ppkg/packed/${{ github.event.inputs.bundle-type }}

      - run: scp -i $VAGRANT_CWD/.vagrant/machines/default/virtualbox/private_key -o StrictHostKeyChecking=no -r -P 2222 vagrant@127.0.0.1:/home/vagrant/.ppkg/packed/${{ github.event.inputs.package-name }}-*-openbsd-amd64.tar.xz .

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}---openbsd-amd64.${{ github.event.inputs.profile }}${{ github.event.inputs.bundle-type }}
          path: '*${{ github.event.inputs.bundle-type }}'
