name: manually build package for macos

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-version:
        description: input a target version to be built
        required: false
        default: '14.0'

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - arm64

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-x'

      bundle-type:
        description: choose a pack type
        type: choice
        options:
          - tar.xz
          - tar.lz
          - tar.gz
          - tar.bz2
          - zip

jobs:
  build:

    runs-on: macos-14

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install macos-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }}
      - run: ./ppkg bundle  macos-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} ${{ github.event.inputs.bundle-type }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}-macos-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}.${{ github.event.inputs.bundle-type }}
          path: '*${{ github.event.inputs.bundle-type }}'
