name: manually build package for linux-musl

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - aarch64
          - ppc64le
          - riscv64
          - loongarch64
          - s390x

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-x'

      bundle-type:
        description: choose a bundle type
        type: choice
        options:
          - .tar.xz
          - .tar.lz
          - .tar.gz
          - .tar.bz2
          - .zip

      static:
        description: create fully statically linked executables
        type: boolean
        default: false

      portable:
        description: bundle all needed libraries into the archive
        type: boolean
        default: false

      publish:
        description: publish as GitHub release
        type: boolean
        default: false

      tagname:
        description: GitHub release tagname
        required: false



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - name: create run.sh
        run: |
          if [ ${{ github.event.inputs.static }} = true ] ; then
            FSLE=--static
          else
            FSLE=
          fi

          if [ ${{ github.event.inputs.portable }} = true ] ; then
            PORTABLE=--portable
          else
            PORTABLE=
          fi


          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          export GITHUB_ACTIONS=true

          run ./ppkg setup --syspm
          run ./ppkg update
          run ./ppkg install ${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }} $FSLE
          run ./ppkg bundle  ${{ github.event.inputs.package-name }} ${{ github.event.inputs.bundle-type }} $PORTABLE
          EOF

      - run: curl -LO https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -d /alpine -a ${{ github.event.inputs.target-arch }}
      - run: /alpine/enter-chroot sh run.sh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}---linux-musl-${{ github.event.inputs.target-arch }}.${{ github.event.inputs.profile }}${{ github.event.inputs.bundle-type }}
          path: '*${{ github.event.inputs.bundle-type }}'


  publish:
    needs: build
    if: github.event.inputs.publish == 'true'

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
      - run: git -c init.defaultBranch=master init
      - run: git remote add origin ${{ github.repositoryUrl }}

      - run: sha256sum *${{ github.event.inputs.bundle-type }} > notes.md

      - run: |
          if [ -z "${{ github.event.inputs.tagname }}" ] ; then
            TAGNAME="$(ls *${{ github.event.inputs.bundle-type }})"
          else
            TAGNAME=${{ github.event.inputs.tagname }}
          fi

          gh release create "$TAGNAME" *${{ github.event.inputs.bundle-type }} --title "$TAGNAME" --notes-file notes.md
